### ISSUE TITLE
[meeting] 2018/11/27 first meeting

### ISSUE THREAD

**Issue by Yangseungchan** [18-2-SKKU-OSS/2018-2-OSS-E3#1]
오늘 미팅을 통해 각자의 역할과 앞으로의 활동 계획 및 주기를 정했습니다. 각자 코멘트를 통해 앞으로의 활동에 대해 간략히 설명해 주세요.

**Comment by iiVSX** [comment]
2. 전체적인 순서는 코드분석 (황석진) -> 형태소에 대한 연구(오세훈) -> 예외문장 찾기(강보영) -> 예외 문장에 대한 코드 수정 (조영훈) -> 코드의 효율성 개선(김근하) -> Issue 및 wiki 전담 처리 (양승찬)

**Comment by iiVSX** [comment]
앞으로 매주 각 단계에서 자신이 한 활동을 issue와 wiki로 정리하고, 이에 대해 모두 그에 대해 피드백을 주는 방식으로 프로젝트를 진행하기로 함.

**Comment by seouuuukjin** [comment]
네

**Comment by KIMKEUNHA** [comment]
코드의 효율성 증대에 대해 어떻게 할지 몰랐지만 ,오세훈학생의 친절한 설명을 통해 주석과 변수관리를 체계적으로 계획했습니다.

**Comment by KIMKEUNHA** [comment]
ㄳ

**Comment by seouuuukjin** [comment]
저는 코드분석 역할을 맡았습니다. 제가 할일은 C++로 작성된 KIWI 프로젝트를 코드를 직접보며 KIWI가 어떠한 원리로 작동하는지  분석하여 정리해 업로드 하도록 하겠습니다.

**Comment by 2017312548** [comment]
코드를 실행시켜 다양한 예시 문장들을 넣어봄으로써 예외가 되는 경우가 있는지 확인할것이다. 신조어나 오탈자, 유행어, 줄임말 등의 경우에 대해 집중적으로 실행시켜 볼 계획이다.

**Comment by KIMKEUNHA** [comment]
> 저는 코드분석 역할을 맡았습니다. 제가 할일은 C++로 작성된 KIWI 프로젝트를 코드를 직접보며 KIWI가 어떠한 원리로 작동하는지 분석하여 정리해 업로드 하도록 하겠습니다.

**Comment by KIMKEUNHA** [comment]
> 저는 코드분석 역할을 맡았습니다. 제가 할일은 C++로 작성된 KIWI 프로젝트를 코드를 직접보며 KIWI가 어떠한 원리로 작동하는지 분석하여 정리해 업로드 하도록 하겠습니다.

풉키

**Comment by iiVSX** [comment]
저는 황석진 학생의 분석한 코드를 바탕으로 보완해야할 형태소를 공부하여, 이를 wiki에 올리고 issue화하여 다음 수정 때  이것이 반영될 수 있도록 하겠습니다.

**Comment by whdudgns412** [comment]
바로 앞 예외 코드 부분 찾기 과정에서 수정할 부분을 전달받아 '예외 문장에 대한 코드 수정' 파트에 대한 오류 수정 및 디버깅을 통하여 프로젝트 개선에 기여할 계획입니다.

**Comment by iiVSX** [comment]
오늘 이 이슈를 바탕으로 wiki를 양승찬 학생이 올려주시기 바랍니다.

**Comment by KIMKEUNHA** [comment]
https://github.com/sea-boat/TextAnalyzer 이거 영어 단어 분석기인데 한번 참고하세요 >.ㅇ

**Comment by KIMKEUNHA** [comment]
코드분석 빨리해주셔야 프로젝트가 진행됩니다

**Comment by KIMKEUNHA** [comment]
대답합니다 황석진군

**Comment by whdudgns412** [comment]
조용히 좀 해주셨으면 좋겠네요

**Comment by KIMKEUNHA** [comment]
오늘은 양승찬군이 빠르게 문서를 작성해야 집으로 갑니다
응원하세요 갈구세요
