### ISSUE TITLE
[request] 고유명사 분석 오류 케이스

### ISSUE THREAD

**Issue by 2017312548** [18-2-SKKU-OSS/2018-2-OSS-E3#13]
**Describe the bug**
아래의 Screenshots을 보면 "문재인"과 "이재명"을 고유명사로 분석하지 않고 각각 문/NNG + 재인/NNG과 이재/NNP + 명/NNG으로 분석하였다.

**Expected behavior**
많은 사람들이 아는 유명인의 이름을 고유명사로 분석해야한다. 

**Screenshots**
<img width="453" alt="dfd" src="https://user-images.githubusercontent.com/43449786/49225988-c1144380-f428-11e8-8789-2287f703270f.PNG">

<img width="451" alt="dsa" src="https://user-images.githubusercontent.com/43449786/49226007-d2f5e680-f428-11e8-8af8-82c3eb2aecab.PNG">

**Desktop (please complete the following information):**
 - OS: Chrome
 - Browser: Internet Explorer

**Additional context**
"문재인"의 경우 이름안에 "문"이라는 일반명사가 포함되어 있어서 그렇게 분석한것으로 보인다.

**Comment by iiVSX** [comment]
네 감사합니다. 첫번째로 올려주신 기사는 위 테스트 케이스를 중점적으로 오류를 찾아내되, 미처 찾지 못하신 부분에 대해서도 형태소를 분석하여 올리도록 하겠습니다.
