### ISSUE TITLE
[bug] 프로그램의 버그에 대한 신문기사 예를 통한 분석

### ISSUE THREAD

**Issue by iiVSX** [18-2-SKKU-OSS/2018-2-OSS-E3#17]
강보영 학생의 테스트 실행 결과를 바탕으로, 오류가 나는 문장에 대한 형태소에 대한 분석을 진행하였고, 잘못 분석한 형태소에 대해서는 연구를 통해 올바른 분석 문장이 무엇인지 조사하였습니다.
1.
“문재인”의 경우, 고유명사이기 때문에 성과 이름을 나누어 적을 필요가 없습니다. 따라서, 이름을 ‘문’이라는 명사와 ‘재인’이라는 고유명사로 나누는 Kiwi의 문제점을 보완할 필요가 있다고 느낍니다.
2.
“지난주”의 경우, 지나 + ㄴ + 주 의 형태로 나누어져야 한다. 물론, 기사에서 ‘지난 주’를 ‘지난주’로 표기를 잘못한 문제도 있지만, 이 또한 개선 되어야할 방안이라고 생각한다.
그리고 3.2%의 경우 3과 2는 개별적인 수사라고 인식하여 3.2를 ‘3’, ‘.’, ‘2’로 나누어 분석하는 경우가 있는데, 이는 3.2 하나의 수로 인식되어야 하므로, 소수에 대한 처리도 필요할 것으로 요망됨.
‘잘함’의 경우에도 ‘잘’이라는 부사와 ‘하-‘라는 동사와 ‘ㅁ’의 명사형 전성어미가 합쳐진 것이므로, 의존형태소에 대한 형태에 대한 분석도 필요함. 반대로, ‘잘하는 편’에서 나타나 듯이, ‘잘하는 편’은 ‘잘’ + ‘하-‘ + ‘는’ + ‘편’ 으로 정상적으로 분석을 잘한 것으로 보아, 명사형 전성어미에 대한 처리가 안됐다.
3.
앞에서 언급했던 소수점 문제가 나타남.
‘잘못함’에서 ‘잘못’ + ‘함’ 으로 인식하는 것을 보아하니 ‘잘’ + ‘못’ 두개의 부사가 합쳐진 경우, 인식을 못하는 것으로 추정됨.
4.
‘내인’을 ‘내이’ + ‘이’ + ‘ㄴ’ 으로 분석하는 치명적인 오류가 발생함. 이는 ‘이’ 를 두 번 인식한 것으로 추정된다. 올바른 분석은 ‘내’ + ‘이’ + ‘ㄴ’ 으로 이는 특별한 예외조항으로 처리해야 할 것 같다.
‘엇갈리다’에서 ‘엇-’ 은 접두사로 따로 분리해야 하고, ‘갈리다’는 ‘가르-‘ + 피동 접사 ‘이’ + ‘다’ 이다. 하지만, Kiwi는 이를 하나의 동사인 ‘엇갈리’ + ‘다’로 인식한다. 접사에 대한 구성이 굉장히 안되어 있는 듯 하다.
5.
‘더불어민주당’ 이라는 고유 명사를 ‘더불’ + ‘어’ + ‘민주당’ 으로 인식한다. 유명한 고유명사는 등록이 요함.
‘기울어져’는 ‘기울-‘ + ‘(-어)지’의 보조동사 + ‘어’가 합쳐져 만든 용언의 활용이므로 위에서 언급했듯, 보조용언과 접사에 대한 추가가 필요함.

‘-이라고’는 하나의 조사인데 이를 ‘이’ + ‘라고’의 별개의 조사로 나누는 것은 옳지 않음

9.
‘크지만’은 ‘크-‘ + 어미 ‘지’ + 한정 조사 ‘만’으로 이루어져야 하지만, 이를 ‘크-‘ + ‘지만’으로 분석 중이다. 체언, 용언과 같은 거대한 축을 이루고 있는 것들은 잘 분석하지만, 조사나 어미 등의 분석이 부족해 보임.

10.
‘어려움’은 ‘어려-‘ + ‘우’ + ‘ㅁ’ 이 합쳐진 형태로, 위에서는 ‘어려움’ 으로 하나의 명사로 구분하고 있다. 이는 아까 언급하였던 전성어미의 인식 부재로 일어난 결과라고 생각한다.
‘-이다’는 ‘-이’ + ‘-다’로 분석한 결과와는 달리 ‘-이다’인 하나의 접미사여야 한다.
11.
‘퍼주기’ 는 ‘퍼주’ + ‘기’의 형태로 분석되어야 한다. ‘퍼주기’의 한 단어가 아니다.
12.
앞에서의 ‘문재인’의 예와 비슷하게 ‘이재명’을 ‘이재’ + ‘명’으로 잘못 분석한 예이다. 고유명사에 대한 보완이 필요한 이유를 보여주는 한 예이다.
13.
‘시도해’는 ‘시도-‘ + ‘해’가 아닌 ‘시도-‘ + ‘하’ + ‘어’의 형태로 분석되어야 한다. ‘해’가 명사로 구분되고 있다.

**Comment by 2017312548** [comment]
제가 실행시키면서 읽어보았을때 보다 더 많은 예외 케이스들이 눈에 띄네요.
1, 5, 12, 13 테스트 케이스에 대해서는 공통적으로 정답이 되는 단어 안에 다른 명사(문, 명, 해)가 포함되어 있어 잘못 분석하는것으로 보이고, 이외에도 접사, 부사, 어미에 대한 추가적인 분석이 필요할것같습니다.
