### ISSUE TITLE
[Q&A] 사투리나 시적 허용에 대한 논의

### ISSUE THREAD

**Issue by iiVSX** [18-2-SKKU-OSS/2018-2-OSS-E3#19]
제가 강보영 학생이 예외 케이스를 찾기 위해 테스트한 윤동주 시인의 '별 헤는 밤' 시를 조사하던 중,
의문이 생겼습니다.

"과연 시적 허용이나 사투리의 경우 Kiwi가 분석하게 해야 할까?"

만약 Kiwi의 용도가 번역기나 표준어에 대한 형태소 분석만 가능케하는 용도라면 이러한 기능은 필요 없다고 생각합니다.
다만, 요즘 여러 커뮤니티 들이나 웹상에서는 맞춤법과 어긋나고 신조어, 외래어가 난무하는 시대에서 현실적인 형태소 분석기는 사투리나 시적 허용 그리고 현대인들의 언어도 분석하는 기능을 제공해야 할까요?
여러분들의 생각은 어떠신가요?

**Comment by KIMKEUNHA** [comment]
제 생각에는 분석풀을 따로 두는것이 현명한 판단이라고 생각합니다. 크게 보면 형태소 분석기는 한국어(표준어)라는 언어를 분석하기 위해 만든것 입니다. 사투리나 외래어를 다르게 보면 한국어(표준어)에 속하지 않는 그저 다른 하나의 "언어"라고 표현할 수 있습니다. 그렇기에 저는 한국어(표준어)에 속하지 않는 것들을 위한 업그레이드 보다는 다른 기능을 가진 Kiwi.ver를 만들어야한다고 생각합니다. 조금 더 깊게 설명하자면 어떠한 글이 들어오게 되면 표준어인지 아니면 다른 지방의 사투리가 섞여있는지 지표로 분석하여 표준어위주로 되어있는글이면 그대로, 다른 지방의 방언 위주로 되어있으면 Kiwi(방언버전). 외래어나 신조어로 되어있으면 Kiwi(외래어-신조어버전) 이런 식으로 차이를 두고 분석을 하면 좋겠습니다.
위와 같은 과정 없이 현재의 Kiwi처럼 이용이 된다면 불분명하거나 틀린 정보를 사용자에게 주는것 보다는, 분석하기 어려운 단어들이 많이 등장하면 분석할 수 없다라는 결과를 사용자에게 주는 것이 좋은 방향이라고 생각합니다.

**Comment by KIMKEUNHA** [comment]
지금의 상황에서 현실적으로 말씀드리자면 불분명한 서비스를 광범위하게 제공하기 보다는 분명한 서비스를 위해 범위를 줄이자, 즉 충분한 데이터나 분석할 수 있는 방향을 마련하기 전에는 굳이 저런 기능을 제공하지 않아도 된다고 생각합니다.

**Comment by seouuuukjin** [comment]
개발자의 블로그에도 쓰여있듯이 KIWI는 인터넷 용어나 신조어를 해결해주지못하는 한계를 지니고 처음부터 설계되었는데,
만약 그게 가능하게 하려면 코드전체적으로 뒤엎어야 할거 같습니다

**Comment by whdudgns412** [comment]
애초에 딥러닝처럼 학습하는 알고리즘으로 설계된 프로그램이 아니라면 신조어나 용어, 약어 등은  방대한 데이터베이스 없이는 구별하는데에 한계가 있을 것으로 생각됩니다. KIMKEUNHA님의 말씀처럼 각 문장에 가중치를 두고, 식별할 수 없는 단어가 일정 이상 있는 것으로 확인되면 "구별할 수 없음" 같은 결과를 내놓는게 가장 적절한 것으로 보입니다. 오답률을 줄이는 편이 더 낫겠죠.

**Comment by 2017312548** [comment]
기존의 Kiwi에 사투리와 시적표현에 대한 분석 기능을 추가한다면 그로 인한 또다른 예외케이스들이 발생할수 있을것같습니다. 특히 시적표현 같은 경우는 독자에 따라 어떻게 해석하는지 느끼는지가 달라질 수 있기 때문에 시적표현의 경우에는 형태소 분석에 한계가 있을수밖에 없을것입니다. 하지만 외래어 같은 경우는 위의 김근하 학생의 말처럼 한국어(표준어)에는 속하지 않지만 요즘 빈번히 쓰이기도 하고 아래와 같이 국립국어원의 외래어표기법으로 객관적인 규정이 존재하기 때문에 분석 기능을 제공하여도 좋을것같습니다.
외래어 표기법 규정 링크: https://www.korean.go.kr/front/page/pageView.do?page_id=P000104&mn_id=97
