### ISSUE TITLE
[meeting] 2018/12/11 프로젝트 발표일

### ISSUE THREAD

**Issue by seouuuukjin** [18-2-SKKU-OSS/2018-2-OSS-E3#2]
그전까지 프로젝트 완료 요망

**Comment by iiVSX** [comment]
11일이 발표일이니 적어도 9-10일 쯤에는 완료하고 완료된 내용을 바탕으로 ppt 제작을 하여 발표를 하는 것이 바람직하다고 생각함. 물론, ppt는 양승찬 학생이 제작할 것입니다.

**Comment by KIMKEUNHA** [comment]
역시 조장님 화이팅입니다

**Comment by seouuuukjin** [comment]
그럼 발표전까지 발표자료(ppt) 승찬이가 올려주면 좋을꺼 같아요

**Comment by KIMKEUNHA** [comment]
그가 발표를 한다면 심금을 울리겠네요

**Comment by whdudgns412** [comment]
제목에 공백들어간거 너무 불-편해서 수정했습니다
