### ISSUE TITLE
[request] 고유명사(이름) 관련

### ISSUE THREAD

**Issue by KIMKEUNHA** [18-2-SKKU-OSS/2018-2-OSS-E3#20]
대부분의 고유명사에 대해 Kiwi는 문제점을 가지고 있습니다. 저희가 많은 문제들을 한번에 해결하지는 못하지만 사람이름, 평균적으로 3글자에 대한 분석 문제를 해결할 수 있다고 생각합니다. 여러분의 생각은 어떠하신지 궁금합니다. 하위 프로젝트로 이 문제를 해결할 방안을 찾아보는 것은 어떨까 합니다.

**Comment by seouuuukjin** [comment]
좋은거 같아요 찾아서 안나와도 그거대로 좋은거고 나오면 더 좋은거니까요

**Comment by whdudgns412** [comment]
이 논의 사항은 매우 중요한 안건입니다. 특히 형태소 분석기와 같은 프로그램에서 고유명사를 인식하는 것이 까다로운 일인데, 이를 "개체명 인식" 기술이라고 합니다. LSTM CRF 기술을 통한 개체명 인식법이 있고, 데이터베이스 딕셔너리를 참조하여 고유명사를 식별하는 방법이 있습니다.

링크: TEXTOM 3.0  http://blog.naver.com/PostView.nhn?blogId=textom&logNo=220942822228

**Comment by 2017312548** [comment]
정보 검색에서 개체명이 주요 검색 대상이 빈번히 되기 때문에 예외 케이스 수정을 시도해 보는게 좋을것같습니다. 특히 위의 한국 이름 관련 사이트 혹은 데이터베이스를 딕셔너리를 참고하면 지난 기사 분석 테스트 케이스 문제를 해결할 수 있기 때문에 Kiwi의 성능을 높일 수 있을것으로 보입니다.

**Comment by iiVSX** [comment]
네 제가 지난번에도 말했듯 고유명사에 대해서 인명사전이나 고유명사 데이터베이스를 구축해서 사용하게 추천하는 것도 괜찮은 것 같아요
