### ISSUE TITLE
[Info] 타 형태소 분석기 알고리즘

### ISSUE THREAD

**Issue by whdudgns412** [18-2-SKKU-OSS/2018-2-OSS-E3#21]
http://kkma.snu.ac.kr/documents/?doc=algorithm

**Comment by whdudgns412** [comment]
꼬꼬마라는 이름을 가진 또 다른 한글 형태소 분석기입니다. 지금 코드 분석이 완전히 되었는지는 아직 전달받지 못했는데, 위 링크의 알고리즘이 코드 해석에 도움이 될 수 있을까 해서 업로드했습니다. 어디까지나 참고용입니다.. 전혀 다른 알고리즘일 수 있으니

**Comment by Yangseungchan** [comment]
해당 알고리즘은 이미 자료로 작성되고 commit되었으니 다른 알고리즘을 가져와주세요
