### ISSUE TITLE
[notice] 현재 팀에 등록된 계정만을  이용해주시기 바랍니다

### ISSUE THREAD

**Issue by Yangseungchan** [18-2-SKKU-OSS/2018-2-OSS-E3#22]
![default](https://user-images.githubusercontent.com/38908080/49339919-2ad85b80-f67c-11e8-898e-db4f6bd2db33.png)

위와 같이 등록되지 않은 계정을 이용하지 않으시면 누구의 활동인지 확인하기 어렵기 때문에 반드시 팀에 등록된 계정을 이용해주시기 바랍니다

등록된 계정은 다음과 같습니다

![default](https://user-images.githubusercontent.com/38908080/49339947-ae924800-f67c-11e8-9f1d-2f60869226fd.png)

**Comment by iiVSX** [comment]
저도 누구인지 모르겠는데 누가 참여하고 있는거죠...?

**Comment by KIMKEUNHA** [comment]
제 계정인데 닉네임설정만 바꾸면 되나요

**Comment by KIMKEUNHA** [comment]
시험해보겠습니다.
