### ISSUE TITLE
[meeting] 2주차 회의

### ISSUE THREAD

**Issue by iiVSX** [18-2-SKKU-OSS/2018-2-OSS-E3#25]
commmit 내역
이전에 토의해온 고유명사 해결 문제에 대해서 수집된 의견들을 바탕으로 향후 고유명사 인식문제에 대한 해결책을 정리 [오세훈]

코드분석 자료들을 파일로 옮겨 정리 [오세훈]

알고리즘 분석 자료들을 모아 파일에 옮겨 정리 [오세훈]

프로젝트의 SDK가 15버전으로 맞추어져 있어, 이를 17버전에 맞추어 프로젝트 솔루션 대상을 변경하고 프로젝트 속성을 17에 맞추어 변경함 [오세훈]

SNS 글들로 해당 프로젝트를 테스트한 결과물들을 기존 테스트 파일에 추가하고 정리함 [오세훈]

issue 내역
일부 커밋에서 팀에 등록된 계정으로 커밋이 이루어지지 않고있어 등록된 계정만을 이용하도록 공지함 [양승찬]

SNS 글들에 대해서도 Kiwi가 잘 작동하는지 테스트를 진행 [강보영]

SNS 예시 글들에 대해서 발생한 Kiwi의 버그 예들에 대해서 정리 [오세훈]

**Comment by seouuuukjin** [comment]
코드분석 - 한글처리 알고리즘 [황석진]

**Comment by KIMKEUNHA** [comment]
현재 소규모 프로젝트로 고유명사 판단 프로그램을 간단하게 짜려고 합니다. 향후 KIWI에 적용 가능할지는 모르겠지만 관련 정보들은 도움이 될것이라고 생각됩니다.

**Comment by seouuuukjin** [comment]
코드분석 - Trie 자료구조와 단어저장및 탐색-미완성 [황석진]

**Comment by 2017312548** [comment]
저는 좀 더 다양한 종류의 글들에 대해 테스트를 해보고 어떤 경우에 예외케이스가 발생되는지 확인해 볼 계획입니다.

**Comment by whdudgns412** [comment]
Kiwi 코드 분석 중 Probability Parameter의 특정 extern 클래스의 선언문을 찾을 수 없음 - 현재 코드 전체 컴파일 실패했습니다. 컴파일 오류 원인 분석중 [조영훈]
