### ISSUE TITLE
[notice] 내일은 발표날입니다

### ISSUE THREAD

**Issue by sxungchxn** [18-2-SKKU-OSS/2018-2-OSS-E3#26]
다른 발표자료 준비없이 깃허브를 이용해서 발표를 해야하며 전원 발표 하기로 하였기 때문에
내일 발표시 자신이 한 기록들을 보여줄 수 있도록 그동안의 자신이 해온 기록들을 한번씩만 살펴보시기 바랍니다

**Comment by seouuuukjin** [comment]
네
