### ISSUE TITLE
[info] 한글 자음/모음 를 분리/조합 하는 라이브러리 관련 프로젝트 링크입니다.

### ISSUE THREAD

**Issue by seouuuukjin** [18-2-SKKU-OSS/2018-2-OSS-E3#3]
https://github.com/e-/Hangul.js

**Comment by iiVSX** [comment]
네 알겠습니다 좋은 정보 감사합니다.

**Comment by KIMKEUNHA** [comment]
https://github.com/sea-boat/TextAnalyzer

**Comment by whdudgns412** [comment]
https://github.com/imotov/elasticsearch-analysis-morphology
ElasticSearch를 통하여 Lucene 프레임워크 및 Java 언어 기반으로 영어와 러시아의 형태소를 분석하는 프로젝트입니다.
